/**
 * Created by wanglei on 17/5/23.
 */
export const POP_OVER_CREATE_TEAM = 'POP_OVER_CREATE_TEAM';
export const POP_OVER_DELETE_TEAM = 'POP_OVER_DELETE_TEAM';
export const POP_OVER_CREATE_BOARD = 'POP_OVER_CREATE_BOARD';
export const POP_OVER_RENAME_BOARD = 'POP_OVER_RENAME_BOARD';
export const POP_OVER_LIST_ACTIONS = 'POP_OVER_LIST_ACTIONS';
