export const HIDE_POP_OVER = 'HIDE_POP_OVER';
export const SHOW_POP_OVER_CREATE_TEAM = 'SHOW_POP_OVER_CREATE_TEAM';
export const SHOW_POP_OVER_DELETE_TEAM = 'SHOW_POP_OVER_DELETE_TEAM';

export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE';
export const CLEAR_CREATE_TEAM_ERR = 'CLEAR_CREATE_TEAM_ERR';

export const QUERY_TEAM_SUCCESS = 'QUERY_TEAM_SUCCESS';
export const QUERY_TEAM_FAILURE = 'QUERY_TEAM_FAILURE';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAILURE = 'UPDATE_TEAM_FAILURE';
export const CLEAR_UPDATE_TEAM_ERR = 'CLEAR_UPDATE_TEAM_ERR';

export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';

export const SAVE_LIST_NAME_OVER = 'SAVE_LIST_NAME_OVER';
export const HIDE_EDITOR_OVER = 'HIDE_EDITOR_OVER';
export const SHOW_EDITOR_OVER = 'SHOW_EDITOR_OVER';
export const SAVE_EDITOR_OVER = 'SAVE_EDITOR_OVER';
export const ADD_LIST_TO_BOARD_OVER = 'ADD_LIST_TO_BOARD_OVER';
export const ADD_CARD_TO_LIST_OVER = 'ADD_CARD_TO_LIST_OVER';
export const SORT_CARD_LIST_OVER = 'SORT_CARD_LIST_OVER';
export const SORT_CARD_LIST_OVER_CARD = 'SORT_CARD_LIST_OVER_CARD';

