export const HIDE_POP_OVER = 'HIDE_POP_OVER';
export const SHOW_CREATE_TEAM_POP_OVER = 'SHOW_CREATE_TEAM_POP_OVER';

export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE';
export const CREATE_TEAM_CLOSE = 'CREATE_TEAM_CLOSE';
