export const INIT_APP = 'INIT_APP';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const HIDE_POP_OVER = 'HIDE_POP_OVER';
export const CLEAR_POP_OVER_ERR = 'CLEAR_POP_OVER_ERR';
export const POP_OVER_SUBMIT_FAILURE = 'POP_OVER_SUBMIT_FAILURE';
export const SHOW_POP_OVER_CREATE_TEAM = 'SHOW_POP_OVER_CREATE_TEAM';
export const SHOW_POP_OVER_DELETE_TEAM = 'SHOW_POP_OVER_DELETE_TEAM';
export const SHOW_POP_OVER_CREATE_BOARD = 'SHOW_POP_OVER_CREATE_BOARD';

export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';

export const QUERY_TEAM_SUCCESS = 'QUERY_TEAM_SUCCESS';
export const QUERY_TEAM_FAILURE = 'QUERY_TEAM_FAILURE';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAILURE = 'UPDATE_TEAM_FAILURE';
export const CLEAR_UPDATE_TEAM_ERR = 'CLEAR_UPDATE_TEAM_ERR';

export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';

export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';

export const QUERY_BOARD_SUCCESS = 'QUERY_BOARD_SUCCESS';
export const COPY_BOARD_SUCCESS = 'COPY_BOARD_SUCCESS';

export const SAVE_LIST_NAME_OVER = 'SAVE_LIST_NAME_OVER';
export const HIDE_EDITOR_OVER = 'HIDE_EDITOR_OVER';
export const SHOW_EDITOR_OVER = 'SHOW_EDITOR_OVER';
export const SAVE_EDITOR_OVER = 'SAVE_EDITOR_OVER';
export const ADD_LIST_TO_BOARD_OVER = 'ADD_LIST_TO_BOARD_OVER';
export const ADD_CARD_TO_LIST_OVER = 'ADD_CARD_TO_LIST_OVER';
export const SORT_CARD_LIST_OVER = 'SORT_CARD_LIST_OVER';
export const SORT_CARD_LIST_OVER_CARD = 'SORT_CARD_LIST_OVER_CARD';
export const ARCHIVE_CARD_OVER = 'ARCHIVE_CARD_OVER';
export const SHOW_POP_OVER_RENAME_BOARD = 'SHOW_POP_OVER_RENAME_BOARD';
export const RENAME_BOARD_OVER = 'RENAME_BOARD_OVER';
export const SHOW_POP_OVER_LIST_ACTIONS = 'SHOW_POP_OVER_LIST_ACTIONS';
export const ARCHIVE_LIST_OVER = 'ARCHIVE_LIST_OVER';

export const SHOW_POP_OVER_ARCHIVE_BOARD = 'SHOW_POP_OVER_ARCHIVE_BOARD';
export const ARCHIVE_BOARD_SUCCESS = 'ARCHIVE_BOARD_SUCCESS';
